name: Extrair Notícia Principal (CGN)

on:
  workflow_dispatch:
  # Ou agende para rodar todo dia, se quiser:
  # schedule:
  #   - cron: '0 10 * * *'

jobs:
  extrai-noticia:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: npm install

      - name: Executar extração da notícia
        run: node scripts/extrai-noticia.js

      - name: Salvar resultado extraído como artifact
        uses: actions/upload-artifact@v4
        with:
          name: noticia-extraida
          path: noticia_extraida.json
