jobs:
  gerar-e-publicar:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório com autenticação
        run: |
          git clone https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }} .

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm install axios

      - name: Gerar conteúdo com ChatGPT
        run: node gerar-conteudo.js
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Commitar alterações
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add artigo.html
          git commit -m "🤖 Novo artigo gerado automaticamente"
          git push origin HEAD:main
