name: gerar-e-commitar

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 * * * *'

jobs:
  gerar-e-commitar:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório com autenticação
        run: |
          git clone https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }} .

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache do npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-


      - name: Instalar dependências do sistema para o Sharp
        run: sudo apt-get update && sudo apt-get install -y libvips-dev

      - name: Instalar Chromium para Puppeteer
        run: npx puppeteer browsers install chrome

      - name: Instalar dependências
        run: npm install


      - name: Gerar conteúdo com ChatGPT
        run: node gerar-conteudo.js
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
          UNSPLASH_ACCESS_KEY: ${{ secrets.UNSPLASH_ACCESS_KEY }}

      - name: Ajustar remote com token
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }} 

      - name: Commitar alterações
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "⚠️ Nada para commitar, encerrando."
          else
            git commit -m "📝 Novo artigo com estilo refinado"
            git push origin HEAD:main
          fi
