name: Inserir AMP Ads com LFS Enabled

on:
  workflow_dispatch:

jobs:
  inserir-amp-ads-lfs-enabled:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório completo com LFS
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
          submodules: recursive

      - name: Listar todos os arquivos após checkout
        run: ls -R

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependências
        run: npm install

      - name: Inserir AMP Ads nos artigos
        run: node inserir-amp-ads.js

      - name: Commitar alterações
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Inserido AMP Ads com Node.js puro (sem glob)" || echo "Nenhuma mudança"
          git push
